resources:
- repo: self
  clean: true
queue:
  name: DotNetCore-Windows
  timeoutInMinutes: 360
  demands: 
  - msbuild
  - visualstudio
  - DotNetFramework

variables:
  BuildPlatform: 'Any CPU'
steps:
- task: NuGetCommand@2
  inputs:
    command: custom
    arguments: 'locals all -clear'

- task: NuGetRestore@1
  inputs:
    solution: 'build\ToolsetPackages\InternalToolset.csproj'
    feed: '8f470c7e-ac49-4afe-a6ee-cf784e438b93'

- task: CmdLine@1
  inputs:
    filename: mkdir
    arguments: 'Binaries\$(BuildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: 'src/Tools/MicroBuild/Build.proj'
    vsVersion: 15.0
    msbuildArgs: >- 
        /p:TreatWarningsAsErrors=true 
        /p:DeployExtension=false 
        /p:TrackFileAccess=false
        /p:OfficialBuild=true 
        /p:VisualStudioVersion=14.0 
        /flp1:Summary;Verbosity=diagnostic;Encoding=UTF-8;LogFile=$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\Roslyn.log 
        /flp2:WarningsOnly;Verbosity=diagnostic;Encoding=UTF-8;LogFile=$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\Roslyn.wrn 
        /flp3:ErrorsOnly;Verbosity=diagnostic;Encoding=UTF-8;LogFile=$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\Roslyn.err 
        /p:RoslynMyGetApiKey=$(Roslyn.MyGetApiKey) 
        /p:RoslynNuGetApiKey=$(Roslyn.NuGetApiKey) 
        /p:RoslynGitHubEmail=$(Roslyn.GitHubEmail) 
        /p:RoslynGitHubToken=$(Roslyn.GitHubToken) 
        /p:RoslynGitHubUserName=$(Roslyn.GitHubUserName) 
        /p:PublishStableVersions=false 
        /p:VersionStampToPublish=prerelease
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    maximumCpuCount: true
    logProjectEvents: false

